import Image from "next/image";
import { requireWorkspaceActor } from "@/application/identity";
import { getTeacherWorkspace } from "@/application/queries";
import { CandidateForm, RetryForm, RetryResultReviewForm, ReviewForm, SourceRightsForm } from "@/components/ClientActions";
import { Badge, Card, Empty, SurfaceHeader } from "@/components/ui";

export const dynamic = "force-dynamic";

export default async function TeacherPage() {
  const actor = await requireWorkspaceActor(["TEACHER", "ADMIN"], "Teacher Workspace");
  const workspace = await getTeacherWorkspace(actor);
  return <>
    <SurfaceHeader eyebrow="Teacher Workspace" title="Inspect, correct and resume" description="Every Review is an authenticated human command over a course-scoped Attempt and Observation." />
    <div className="showcase-banner"><Badge tone="warn">Synthetic showcase data</Badge> CAPABILITY_UNAVAILABLE observations are review-required states, not automated Diagnoses.</div>
    <div className="stack">{workspace.queue.map((row) => {
      const observationId = String(row.observation_id);
      const reviewId = row.review_id ? String(row.review_id) : null;
      const reviewDecision = row.review_decision ? String(row.review_decision) : null;
      const waitingThread = row.waiting_thread_id ? String(row.waiting_thread_id) : null;
      const fileAssetId = row.file_asset_id ? String(row.file_asset_id) : null;
      const fileMediaType = row.file_media_type ? String(row.file_media_type) : null;
      return <Card key={observationId} eyebrow={String(row.learner_name)} title={String(row.task_title)}>
        <div className="metric-grid"><div><small>Attempt</small><p>{String(row.prompt)}</p><strong>{String(row.response)}</strong></div><div><small>Observation</small><p>{String(row.summary)}</p><Badge tone="warn">{String(row.observation_source)}</Badge></div><div><small>Source refs</small><pre>{JSON.stringify(row.source_refs, null, 2)}</pre></div></div>
        {fileAssetId ? <article className="evidence-card"><strong>Original learner upload</strong><p><a href={`/api/files/${fileAssetId}`} target="_blank" rel="noreferrer">Open {String(row.file_name)}</a></p>{fileMediaType?.startsWith("image/") ? <Image unoptimized src={`/api/files/${fileAssetId}`} alt={`Original learner Attempt: ${String(row.file_name)}`} width={640} height={480} style={{ width: "100%", height: "auto" }}/> : null}<div className="metric-grid"><div><small>Extraction / transcription</small><p>{String(row.file_extraction_text ?? "Unavailable")}</p></div><div><small>Derived model interpretation</small><p>{String(row.file_interpretation ?? "Unavailable")}</p><Badge tone={row.file_interpretation_status === "AVAILABLE" ? "good" : "warn"}>{String(row.file_interpretation_status)}</Badge></div></div><small>The original upload and derived interpretation are separate. The interpretation is not a TeacherReview or deterministic Diagnosis.</small></article> : null}
        {reviewDecision === "ESCALATE" ? <div data-testid="terminal-escalation"><Badge tone="bad">ESCALATED · terminal</Badge><p>This human Review requires specialist resolution. Retry and Component candidate actions are unavailable for this Observation.</p></div> : waitingThread ? <ReviewForm threadId={waitingThread} expectedVersion={Number(row.waiting_interrupt_version)}/> : reviewId ? <><RetryForm observationId={observationId} reviewId={reviewId}/><CandidateForm observationId={observationId}/></> : <Badge tone="bad">No resumable Review workflow</Badge>}
      </Card>;
    })}{workspace.queue.length === 0 ? <Empty>No course-scoped observations.</Empty> : null}</div>
    <div className="workspace-grid"><Card eyebrow="Reviewed capability signals" title="Course-scoped failure codes">{workspace.patterns.map((pattern) => <p key={String(pattern.pattern)}><strong>{String(pattern.pattern)}</strong> · {String(pattern.count)} reviewed capability observations · {String(pattern.learners)} learners</p>)}{workspace.patterns.length === 0 ? <Empty>No reviewed CAPABILITY observation with a failure code is available. Unavailable, unreviewed and null-code observations are not aggregated.</Empty> : null}</Card><Card eyebrow="Retry results" title="Human Review before Outcome">{workspace.pendingWorkflows.filter((run) => run.interruptType === "RETRY_RESULT_REVIEW_REQUIRED").map((run) => <RetryResultReviewForm key={run.id} threadId={run.threadId} expectedVersion={run.interruptVersion}/>)}{workspace.pendingWorkflows.every((run) => run.interruptType !== "RETRY_RESULT_REVIEW_REQUIRED") ? <Empty>No retry result is waiting for Review.</Empty> : null}</Card></div>
    <Card eyebrow="Source governance" title="Uploaded learning-material rights and ingestion">{workspace.sourceReviews.map(({ source, asset, task }) => <article className="evidence-card" key={source.id}><strong>{source.title}</strong><p>{task.title} · {asset.originalName}</p><div className="header-actions"><Badge tone={asset.ingestionStatus === "EXTRACTED" ? "good" : asset.ingestionStatus === "FAILED" ? "bad" : "warn"}>Ingestion · {asset.ingestionStatus}</Badge><Badge tone={source.rightsAuthorizationStatus === "APPROVED" ? "good" : source.rightsAuthorizationStatus === "DENIED" ? "bad" : "warn"}>Rights · {source.rightsAuthorizationStatus}</Badge></div><a href={`/api/files/${asset.id}`} target="_blank" rel="noreferrer">Inspect original upload</a>{asset.mediaType.startsWith("image/") ? <><div className="metric-grid"><div><small>Model-derived visible-content transcription</small><p>{asset.extractionText ?? "Unavailable"}</p></div><div><small>Separate model interpretation</small><p>{asset.interpretation ?? "Unavailable"}</p><Badge tone={asset.interpretationStatus === "AVAILABLE" ? "good" : "warn"}>{asset.interpretationStatus}</Badge></div></div><small>The original image remains the cited Source. Rights approval can materialize its transcription as Evidence; interpretation is excluded.</small></> : <p>{asset.failureMessage ?? asset.extractionText?.slice(0, 500) ?? "No extracted content is available."}</p>}{source.rightsAuthorizationStatus === "REVIEW_REQUIRED" ? <SourceRightsForm sourceId={source.id} currentRights={source.rights}/> : <small>Terminal authenticated human rights decision recorded.</small>}</article>)}{workspace.sourceReviews.length === 0 ? <Empty>No uploaded course material is awaiting or carrying a rights decision.</Empty> : null}</Card>
  </>;
}
