import { withWorkspaceActor } from "@/application/identity";
import { getEngineeringWorkspace } from "@/application/queries";
import { RunFrameworkContractChecksButton } from "@/components/ClientActions";
import { Badge, Card, Empty, SurfaceHeader } from "@/components/ui";
import { WORKFLOW_CATALOG } from "@/workflows/catalog";

export const dynamic = "force-dynamic";

export default async function EngineeringPage() {
  return withWorkspaceActor(["ENGINEER", "ADMIN"], "Engineering Workspace", async (actor) => {
  const workspace = await getEngineeringWorkspace(actor);
  return <>
    <SurfaceHeader eyebrow="Engineering / Inspection" title="Inspect what actually ran" description="Operational workflow, retrieval and framework/core contract-check records are physically separate from canonical Product State." actions={<RunFrameworkContractChecksButton/>}/>
    <div className="showcase-banner"><Badge tone="warn">Honest service status</Badge> Unavailable telemetry and adapters remain unavailable; no values are synthesized.</div>
    <div className="metric-grid">{Object.entries(workspace.serviceStatus).map(([service, status]) => <Card key={service} eyebrow={service} title={status}><Badge tone={["UNAVAILABLE", "NOT_IMPLEMENTED", "NOT_CONFIGURED", "BLOCKED"].includes(status) ? "warn" : "info"}>{status}</Badge></Card>)}</div>
    <Card eyebrow="LangGraph" title="Graph and interrupt inventory">{WORKFLOW_CATALOG.map((graph) => <article className="list-row" key={graph.kind}><span><strong>{graph.title}</strong><small>{graph.nodes.join(" → ")}</small></span><Badge>{graph.interrupts.length ? graph.interrupts.join(" · ") : "NO INTERRUPT"}</Badge></article>)}</Card>
    <Card eyebrow="Operational schema" title="Workflow runs">{workspace.runs.map((run) => <article className="list-row" key={run.id}><span><strong>{run.workflowKind}</strong><small>{run.threadId} · v{run.interruptVersion} · {run.interruptType ?? "complete"}</small></span><Badge tone={run.status === "COMPLETED" ? "good" : run.status === "FAILED" ? "bad" : "warn"}>{run.status}</Badge></article>)}{workspace.runs.length === 0 ? <Empty>No authorized course workflow records.</Empty> : null}</Card>
    <Card eyebrow="Operator recovery" title="Recoverable RESUMING claims"><p>An expired five-minute resume lease is reclaimable by an authorized actor using the current interrupt version. Fresh claims remain protected from concurrent resume.</p>{workspace.staleResumingRuns.map((run) => <article className="list-row" key={run.id}><span><strong>{run.workflowKind}</strong><small>{run.threadId} · lease expired {run.resumeLeaseExpiresAt?.toISOString() ?? "timestamp unavailable"} · claim v{run.resumeClaimVersion}</small></span><Badge tone="warn">RECLAIMABLE</Badge></article>)}{workspace.staleResumingRuns.length === 0 ? <Empty>No expired resume leases in authorized courses.</Empty> : null}</Card>
    <div className="workspace-grid"><Card eyebrow="Retrieval inspection" title="Governed lexical, embedding and reranking runs">{workspace.retrieval.map((run) => <article key={run.id}><strong>{run.query}</strong><pre>{JSON.stringify({ retrievalMode: run.retrievalMode, embeddingStatus: run.embeddingStatus, embeddingModel: run.embeddingModel, rerankerStatus: run.rerankerStatus, rerankerModel: run.rerankerModel, selectedEvidenceIds: run.selectedEvidenceIds, rankingEvidence: run.rankingEvidence, missingSignal: run.missingSignal, latencyMs: run.latencyMs }, null, 2)}</pre></article>)}{workspace.retrieval.length === 0 ? <Empty>No retrieval run recorded.</Empty> : null}</Card><Card eyebrow="Framework/core contract checks" title="Versioned implementation contracts"><p>These checks cover framework and core implementation contracts only. They are not product, pedagogy or learning-effectiveness Eval.</p>{workspace.evaluations.map((run) => <p key={run.id}><Badge tone={run.status === "PASS" ? "good" : "bad"}>{run.status}</Badge> {run.dataset}@{run.datasetVersion} · {run.passed} passed / {run.failed} failed</p>)}{workspace.evaluations.length === 0 ? <Empty>No framework/core contract-check dataset has run.</Empty> : null}</Card></div>
    <Card eyebrow="Model and multimodal calls" title="Provider execution ledger">{workspace.models.map((run) => <article className="list-row" key={run.id}><span><strong>{run.callType} · {run.provider}/{run.model}</strong><small>{run.inputTokens ?? "?"} input · {run.outputTokens ?? "?"} output · {run.latencyMs.toFixed(1)} ms{run.failureCode ? ` · ${run.failureCode}` : ""}</small></span><Badge tone={run.status === "SUCCEEDED" ? "good" : run.status === "UNAVAILABLE" ? "warn" : "bad"}>{run.status}</Badge></article>)}{workspace.models.length === 0 ? <Empty>No provider call or unavailable-state record exists for this institution.</Empty> : null}</Card>
    <Card eyebrow="Asset Loop inspection" title="Component evaluations, human decisions and reuse">
      <h3>Versioned system evaluations</h3>{workspace.componentEvaluationRecords.map(({ evaluation, component, version }) => <article className="list-row" key={evaluation.id}><span><strong>{component.title} · v{version.version}</strong><small>{evaluation.evaluatorKey}@{evaluation.evaluatorVersion} · content {evaluation.contentHash.slice(0, 12)} · {evaluation.sourceAttemptIds.length} distinct signal Attempts</small></span><Badge tone={evaluation.systemStatus === "PASSED" ? "good" : "bad"}>{evaluation.systemStatus}</Badge></article>)}{workspace.componentEvaluationRecords.length === 0 ? <Empty>No Component system evaluation record.</Empty> : null}
      <h3>Authenticated expert decisions</h3>{workspace.componentDecisionRecords.map(({ decision, component, version }) => <article className="list-row" key={decision.id}><span><strong>{decision.action} · {component.title} v{version.version}</strong><small>{decision.rationale} · actor {decision.expertId}</small></span><Badge>{decision.action}</Badge></article>)}{workspace.componentDecisionRecords.length === 0 ? <Empty>No publication or rollback decision.</Empty> : null}
      <h3>Historical reuse deliveries</h3>{workspace.componentDeliveryRecords.map(({ delivery, component, version }) => <article className="list-row" key={delivery.id}><span><strong>{component.title} · pinned v{version.version}</strong><small>Task {delivery.taskId} · Observation {delivery.observationId} · delivered {delivery.createdAt.toLocaleString()}</small></span><Badge tone="good">DELIVERED</Badge></article>)}{workspace.componentDeliveryRecords.length === 0 ? <Empty>No Component support delivery.</Empty> : null}
      <p><Badge tone="warn">AUTOMATED PEDAGOGY/DOMAIN EVAL · UNAVAILABLE</Badge> Deterministic capability fixtures and contract/provenance gates are system checks. Human rubric is recorded separately.</p>
    </Card>
    <Card eyebrow="Checkpoint store" title="LangGraph physical state">{workspace.checkpointCounts.map((row) => <p key={String(row.table_name)}>{String(row.table_name)}: {String(row.count)} {row.status ? `· ${String(row.status)}` : ""}</p>)}</Card>
  </>;
  });
}
