import { useState } from "react";
import { aggregatePatternEvidence } from "../experience/orchestration";
import type { ExperienceState, FoundryCandidateHandoff } from "../experience/types";

type InspectorTab = "EVENTS" | "LEARNER" | "PATTERN" | "DIFF" | "EVALUATION" | "REGISTRY" | "RUNTIME" | "BOUNDARIES";

const tabs: readonly { readonly id: InspectorTab; readonly label: string }[] = [
  { id: "EVENTS", label: "Events" }, { id: "LEARNER", label: "Learner Trace" }, { id: "PATTERN", label: "Pattern Evidence" }, { id: "DIFF", label: "Component Diff" }, { id: "EVALUATION", label: "Evaluation" }, { id: "REGISTRY", label: "Registry" }, { id: "RUNTIME", label: "Runtime" }, { id: "BOUNDARIES", label: "Boundaries" },
];

export function InspectorView({ state, handoff }: { readonly state: ExperienceState; readonly handoff: FoundryCandidateHandoff | null }) {
  const [tab, setTab] = useState<InspectorTab>("EVENTS");
  const pattern = aggregatePatternEvidence(state.evidence);
  const published = state.publishedCandidate;
  return <main className="product-surface inspector-surface">
    <header className="inspector-product-header"><div><p className="surface-kicker">Learning Foundry</p><h1>Engineering Inspector</h1><p>Audit contracts, provenance and runtime evidence without exposing them in user-facing products.</p></div><div className="inspector-health"><span>Session</span><strong>LOCAL / DETERMINISTIC</strong></div></header>
    <nav className="inspector-tabs" aria-label="Engineering inspector">{tabs.map((item) => <button key={item.id} className={tab === item.id ? "active" : ""} onClick={() => setTab(item.id)}>{item.label}</button>)}</nav>
    <section className="inspector-content">
      {tab === "EVENTS" ? <><div className="surface-heading"><div><p className="surface-kicker">Event Log</p><h2>Typed product event timeline</h2></div><span className="status-badge">{state.eventLog.length} EVENTS</span></div><div className="event-timeline">{state.eventLog.length ? state.eventLog.map((event, index) => <article key={event.eventId}><b>{String(index + 1).padStart(2, "0")}</b><div><span>{event.actor}</span><strong>{event.type}</strong><small>{event.occurredAt}</small><pre>{JSON.stringify(event.payload, null, 2)}</pre></div></article>) : <div className="empty-state">No product event has occurred in this session.</div>}</div></> : null}
      {tab === "LEARNER" ? <><div className="surface-heading"><div><p className="surface-kicker">Learner Evidence Trace</p><h2>Current conversation diagnosis</h2></div></div>{state.diagnosis ? <div className="technical-grid"><article><span>Evidence ID</span><code>evidence-mgo-ratio-current</code></article><article><span>Stage</span><code>{state.diagnosis.stage}</code></article><article><span>Failure</span><code>{state.diagnosis.failureCode}</code></article><article><span>Observed / Expected</span><code>{state.diagnosis.observedRatio} / {state.diagnosis.expectedRatio}</code></article></div> : <div className="empty-state">No current learner diagnosis.</div>}</> : null}
      {tab === "PATTERN" ? <><div className="surface-heading"><div><p className="surface-kicker">Pattern Evidence</p><h2>{pattern.occurrenceCount} matching repository traces</h2></div></div><div className="technical-table">{state.evidence.map((item) => <div key={item.id}><code>{item.id}</code><span>{item.conversationId}</span><strong>{item.stage}</strong><strong>{item.failureCode}</strong></div>)}</div></> : null}
      {tab === "DIFF" ? <><div className="surface-heading"><div><p className="surface-kicker">Contract Diff</p><h2>Governed content change</h2></div></div><div className="component-diff"><article><span>v1.0.0</span><h3>mass-ratio hint</h3><p>Compare the coefficients of Mg and MgO.</p></article><article className="new"><span>v1.1.0</span><h3>mass-ratio hint</h3><p>2Mg : 2MgO simplifies to 1:1.<br />Each mole of Mg forms one mole of MgO.</p></article></div></> : null}
      {tab === "EVALUATION" ? <><div className="surface-heading"><div><p className="surface-kicker">Evaluation Checks</p><h2>{handoff?.evaluation?.outcome ?? "NOT RUN"}</h2></div></div>{handoff?.evaluation ? <div className="evaluation-list">{handoff.evaluation.checks.map((check) => <div key={check.id}><span>{check.status}</span><strong>{check.id}</strong></div>)}</div> : <div className="empty-state">No evaluation report is attached.</div>}</> : null}
      {tab === "REGISTRY" ? <><div className="surface-heading"><div><p className="surface-kicker">Registry State</p><h2>{state.registryAccepted ? "Local registry accepted v1.1.0" : "Static registry only"}</h2></div></div><div className="technical-grid"><article><span>Component</span><code>{published ? `${published.id}@${published.version}` : "stoichiometric-product-mass@1.0.0"}</code></article><article><span>Content hash</span><code>{published?.publication.contentHash ?? "not published"}</code></article><article><span>Schema</span><code>{published?.schemaVersion ?? "1.0.0"}</code></article><article><span>Acceptance</span><code>{state.registryAccepted ? "VALIDATED" : "NOT CONNECTED"}</code></article></div></> : null}
      {tab === "RUNTIME" ? <><div className="surface-heading"><div><p className="surface-kicker">Runtime Capability</p><h2>Bounded KP and MASS adapters</h2></div></div><div className="technical-grid"><article><span>Selection policy</span><code>highest compatible semantic version</code></article><article><span>Dynamic source</span><code>{state.registryAccepted ? "local demo registry" : "unavailable"}</code></article><article><span>Static fallback</span><code>enabled</code></article><article><span>Latest version</span><code>{published?.version ?? "1.0.0"}</code></article></div></> : null}
      {tab === "BOUNDARIES" ? <><div className="surface-heading"><div><p className="surface-kicker">Known Boundaries</p><h2>What this demo does not claim</h2></div></div><ul className="boundary-list"><li>Deterministic orchestration</li><li>No external LLM</li><li>Two historical evidence fixtures</li><li>Local single-session state</li><li>No production analytics</li><li>No authenticated identity</li><li>Local demo registry</li><li>Bounded KP and MASS runtime</li></ul></> : null}
    </section>
  </main>;
}
