import { useState } from "react";
import capabilities from "../../config/capabilities/registry.json";
import type { ExperienceState, FoundryCandidateHandoff } from "../experience/types";

type InspectorTab = "AGENT_TRACES" | "AGENTEVAL" | "DIAGNOSIS" | "CONTRACT_CHECKS" | "RUNTIME_VALIDATION" | "REGISTRY" | "BOUNDARIES";
const tabs: readonly { readonly id: InspectorTab; readonly label: string }[] = [
  { id: "AGENT_TRACES", label: "Agent Traces" }, { id: "AGENTEVAL", label: "AgentEval Reports" }, { id: "DIAGNOSIS", label: "Learner Diagnosis" }, { id: "CONTRACT_CHECKS", label: "Component Contract Checks" }, { id: "RUNTIME_VALIDATION", label: "Runtime Validation" }, { id: "REGISTRY", label: "Component Registry" }, { id: "BOUNDARIES", label: "Boundaries" },
];

export function InspectorView({ state, handoff }: { readonly state: ExperienceState; readonly handoff: FoundryCandidateHandoff | null }) {
  const [tab, setTab] = useState<InspectorTab>("AGENT_TRACES"); const latestTrace = state.agentTraces.at(-1); const latestDiagnosis = state.diagnoses.at(-1);
  return <main className="product-surface inspector-surface"><header className="product-header inspector-header"><a className="brand" href="?view=inspector"><span className="brand-mark">LF</span><span>Learning Foundry<small>Engineering Inspector</small></span></a><span className="trusted-chip">Real records only</span></header><nav className="inspector-tabs" aria-label="Engineering Inspector">{tabs.map((item) => <button key={item.id} className={tab === item.id ? "active" : ""} onClick={() => setTab(item.id)}>{item.label}</button>)}</nav><section className="inspector-body">
    {tab === "AGENT_TRACES" ? <><div className="surface-heading"><div><p className="surface-kicker">Agent Traces</p><h1>Provider calls and tool rounds.</h1></div></div>{latestTrace ? <pre className="payload-view">{JSON.stringify(latestTrace, null, 2)}</pre> : <div className="empty-state">No actual Agent trace exists.</div>}</> : null}
    {tab === "AGENTEVAL" ? <><div className="surface-heading"><div><p className="surface-kicker">AgentEval Reports</p><h1>Live reports are generated outside product state.</h1></div></div><div className="empty-state">Run npm run agenteval:live with server-side DeepSeek configuration, then npm run agenteval:report.</div></> : null}
    {tab === "DIAGNOSIS" ? <><div className="surface-heading"><div><p className="surface-kicker">Learner Diagnosis</p><h1>Downstream runtime evidence.</h1></div></div>{latestDiagnosis ? <pre className="payload-view">{JSON.stringify(latestDiagnosis, null, 2)}</pre> : <div className="empty-state">No real Trainer diagnosis exists.</div>}</> : null}
    {tab === "CONTRACT_CHECKS" ? <><div className="surface-heading"><div><p className="surface-kicker">Component Contract Checks</p><h1>Governed component report.</h1></div></div>{handoff?.contractChecks ? <pre className="payload-view">{JSON.stringify(handoff.contractChecks, null, 2)}</pre> : <div className="empty-state">No contract-check report exists.</div>}</> : null}
    {tab === "RUNTIME_VALIDATION" ? <><div className="surface-heading"><div><p className="surface-kicker">Runtime Validation</p><h1>Trainer API boundary.</h1></div></div><div className="inspector-cards"><article><span>Endpoint</span><code>http://127.0.0.1:4177/diagnose</code></article><article><span>Latest trace</span><code>{latestDiagnosis?.traceId ?? "none"}</code></article><article><span>Decision</span><code>{latestDiagnosis?.decision ?? "none"}</code></article></div></> : null}
    {tab === "REGISTRY" ? <><div className="surface-heading"><div><p className="surface-kicker">Component Registry</p><h1>Agent-first and engineering-only capabilities.</h1></div></div><div className="registry-list">{capabilities.capabilities.map((item) => <article key={item.id}><div><span className="card-type">{item.visibility}</span><h2>{item.id}</h2><p>v{item.version} · {item.readiness}</p></div><strong>{item.visibility === "ENGINEERING_ONLY" ? "Legacy regression" : "Agent available"}</strong></article>)}</div></> : null}
    {tab === "BOUNDARIES" ? <><div className="surface-heading"><div><p className="surface-kicker">Boundaries</p><h1>What this local proof claims.</h1></div></div><ul className="boundary-list"><li>DeepSeek calls run only through the server-side gateway</li><li>Missing configuration produces no answer, Trace or product record</li><li>Presets are input only</li><li>Pattern evidence requires actual Agent and Trainer runs</li><li>Library and Schedule writes require human confirmation</li><li>Kp is engineering-only legacy regression metadata</li><li>No authentication or production analytics</li></ul></> : null}
  </section></main>;
}
