import { useState } from "react";
import type { DiagnosticLearningComponent } from "../contracts/diagnostic-component";
import { createDemoEvent } from "../demo/events";
import { aggregatePatternEvidence, createComponentCandidate, promoteComponentCandidate } from "../experience/orchestration";
import type { ExperienceState, FoundryCandidateHandoff } from "../experience/types";
import { runComponentContractChecks } from "../governance/component-contract-checks";
import { publishApprovedComponent } from "../governance/publishing";
import { standardTrainerCapability } from "../runtime/capability";
import { caie9701StandardPack } from "../standards/caie-9701";

type StudioSection = "PATTERNS" | "CANDIDATE" | "CONTRACT_CHECKS" | "REVIEW" | "REGISTRY";
interface StudioViewProps { readonly state: ExperienceState; readonly handoff: FoundryCandidateHandoff | null; readonly onChange: (state: ExperienceState) => void; readonly onHandoffChange: (handoff: FoundryCandidateHandoff) => void; readonly initialSection?: StudioSection }
const nav: readonly { readonly id: StudioSection; readonly label: string }[] = [{ id: "PATTERNS", label: "Pattern Inbox" }, { id: "CANDIDATE", label: "Candidate" }, { id: "CONTRACT_CHECKS", label: "Component Contract Checks" }, { id: "REVIEW", label: "Expert Review" }, { id: "REGISTRY", label: "Registry" }];
const withEvent = (state: ExperienceState, event: ReturnType<typeof createDemoEvent>): ExperienceState => ({ ...state, eventLog: [...state.eventLog, event] });

export function StudioView({ state, handoff, onChange, onHandoffChange, initialSection = "PATTERNS" }: StudioViewProps) {
  const [section, setSection] = useState<StudioSection>(initialSection);
  const [reviewer, setReviewer] = useState(""); const [notes, setNotes] = useState(""); const [publishError, setPublishError] = useState<string | null>(null);
  const pattern = aggregatePatternEvidence(state.diagnoses); const component = handoff?.component ?? null; const checks = handoff?.contractChecks ?? null;
  const canApprove = component?.status === "DRAFT" && checks?.outcome === "PASSED" && reviewer.trim().length > 0 && notes.trim().length > 0;

  function createCandidate() { const created = createComponentCandidate(state); const promoted = promoteComponentCandidate(created); onChange(promoted.state); onHandoffChange(promoted.handoff); setSection("CANDIDATE"); }
  function runChecks() { if (!handoff || handoff.component.status !== "DRAFT") return; const report = runComponentContractChecks(handoff.component, caie9701StandardPack, standardTrainerCapability); onHandoffChange({ ...handoff, contractChecks: report }); onChange(withEvent({ ...state, candidate: state.candidate ? { ...state.candidate, status: "CHECKED" } : null }, createDemoEvent("CANDIDATE_EVALUATED", "FOUNDRY", { candidateId: state.candidate?.id ?? "", outcome: report.outcome }))); }
  function approve() { if (!handoff || !canApprove) return; const approved: DiagnosticLearningComponent = { ...handoff.component, status: "APPROVED", review: { reviewer: reviewer.trim(), reviewedAt: new Date().toISOString(), notes: notes.trim() } }; onHandoffChange({ ...handoff, component: approved }); onChange(withEvent({ ...state, candidate: state.candidate ? { ...state.candidate, status: "APPROVED" } : null }, createDemoEvent("COMPONENT_APPROVED", "SUBJECT_EXPERT", { componentId: approved.id, version: approved.version, origin: "HUMAN_REVIEW" }))); }
  async function publish() { if (!handoff || handoff.component.status !== "APPROVED") return; setPublishError(null); const published = publishApprovedComponent(handoff.component, { publishedAt: new Date().toISOString(), publishedBy: reviewer.trim() }); onHandoffChange({ ...handoff, component: published }); let next = withEvent({ ...state, candidate: state.candidate ? { ...state.candidate, status: "PUBLISHED" } : null, publishedCandidate: published }, createDemoEvent("COMPONENT_PUBLISHED", "FOUNDRY", { componentId: published.id, version: published.version, contentHash: published.publication.contentHash })); onChange(next); try { const response = await fetch("http://127.0.0.1:4175/components", { method: "POST", headers: { "content-type": "application/json" }, body: JSON.stringify(published) }); const result = await response.json() as { ok?: boolean; error?: { message?: string } }; if (!response.ok || !result.ok) throw new Error(result.error?.message ?? "Registry rejected the component."); next = withEvent({ ...next, registryAccepted: true }, createDemoEvent("REGISTRY_COMPONENT_ACCEPTED", "FOUNDRY", { componentId: published.id, version: published.version })); onChange(next); } catch (cause) { setPublishError(cause instanceof Error ? cause.message : "Registry unavailable."); } }

  return <main className="product-surface studio-surface"><header className="product-header studio-header"><a className="brand" href="?view=studio"><span className="brand-mark">LF</span><span>Learning Foundry<small>Foundry Studio</small></span></a><div className="studio-context"><span>Governed product state</span><strong>Actual Agent runs only</strong></div></header><div className="studio-layout"><nav className="studio-nav" aria-label="Foundry Studio"><p className="surface-kicker">Workspace</p>{nav.map((item) => <button key={item.id} className={section === item.id ? "active" : ""} onClick={() => setSection(item.id)}>{item.label}</button>)}</nav><section className="studio-main">
    {section === "PATTERNS" ? <><div className="surface-heading"><div><p className="surface-kicker">Pattern Inbox</p><h1>Learning Pattern Analysis</h1><p>Only matching Learner Diagnosis evidence from actual local Agent runs is counted.</p></div>{pattern.occurrenceCount ? <span className={`threshold-pill ${pattern.thresholdReached ? "reached" : ""}`}>{pattern.occurrenceCount} / {pattern.threshold}</span> : null}</div>{pattern.occurrenceCount ? <article className="pattern-inbox-card"><div className="pattern-summary"><span className="card-type">3 matching actual local runs</span><h2>{pattern.failureCode}</h2><p>{pattern.componentId} · Input origin is recorded per run, including PRESET_INPUT.</p></div><button className="primary" disabled={!pattern.thresholdReached || Boolean(state.candidate)} onClick={createCandidate}>{state.candidate ? "Candidate created" : "Create component candidate"}</button></article> : <div className="empty-state">No learning patterns yet.<br />Patterns appear only after actual Agent runs<br />produce Learner Diagnosis evidence.</div>}</> : null}
    {section === "CANDIDATE" ? <><div className="surface-heading"><div><p className="surface-kicker">Candidate</p><h1>A teacher explicitly creates the candidate.</h1></div><span className="status-badge">{state.candidate?.status ?? "NOT CREATED"}</span></div>{state.candidate ? <div className="candidate-review-grid"><article><span>Source</span><strong>{state.candidate.source}</strong></article><article><span>Matching runs</span><strong>{state.candidate.pattern.occurrenceCount}</strong></article><article className="wide"><span>Trace ids</span><p>{state.candidate.sourceTraceIds.join(" · ")}</p></article><button className="primary" onClick={() => setSection("CONTRACT_CHECKS")}>Open Component Contract Checks</button></div> : <div className="empty-state">No teacher-created candidate.</div>}</> : null}
    {section === "CONTRACT_CHECKS" ? <><div className="surface-heading"><div><p className="surface-kicker">Component Contract Checks</p><h1>Runtime-ready before human review.</h1></div><span className="status-badge">{checks?.outcome ?? "NOT RUN"}</span></div><button className="primary" disabled={!component || component.status !== "DRAFT"} onClick={runChecks}>Run Component Contract Checks</button>{checks ? <div className="contract-check-list">{checks.checks.map((check) => <div key={check.id}><span>{check.status}</span><strong>{check.id.replaceAll("_", " ")}</strong></div>)}</div> : <div className="empty-state">No contract-check report is attached.</div>}</> : null}
    {section === "REVIEW" ? <><div className="surface-heading"><div><p className="surface-kicker">Expert Review</p><h1>Publication requires a named human reviewer.</h1></div><span className="status-badge">{component?.status ?? "NO DRAFT"}</span></div><article className="review-card"><label>Reviewer name<input aria-label="Reviewer name" value={reviewer} onChange={(event) => setReviewer(event.target.value)} /></label><label>Review notes<textarea aria-label="Review notes" value={notes} onChange={(event) => setNotes(event.target.value)} rows={5} /></label><button className="primary" disabled={!canApprove} onClick={approve}>Confirm Expert Review</button></article></> : null}
    {section === "REGISTRY" ? <><div className="surface-heading"><div><p className="surface-kicker">Registry</p><h1>Immutable, runtime-ready versions.</h1></div></div><div className="registry-list"><article><div><span className="card-type">Published</span><h2>Stoichiometric product mass</h2><p>v1.0.0 · Available</p></div><strong>Current</strong></article>{state.publishedCandidate ? <article className="new"><div><span className="card-type">Published</span><h2>{state.publishedCandidate.presentation.title}</h2><p>v{state.publishedCandidate.version} · {state.registryAccepted ? "Available to connected runtimes" : "Awaiting registry"}</p></div><strong>New</strong></article> : null}</div>{!state.publishedCandidate ? <button className="primary" disabled={component?.status !== "APPROVED"} onClick={publish}>Publish candidate</button> : null}{publishError ? <p className="error-message">{publishError}</p> : null}</> : null}
  </section></div></main>;
}
