#!/usr/bin/env node

import { spawn, spawnSync } from "node:child_process";
import { randomBytes } from "node:crypto";
import { existsSync } from "node:fs";
import { chmod, mkdir, readFile, rm, writeFile } from "node:fs/promises";
import net from "node:net";
import { resolve } from "node:path";
import process from "node:process";

const root = process.cwd();
const mode = process.argv[2] ?? "start";
const composeFile = "docker-compose.showcase.yml";
const composeProject = "learning-foundry-showcase";
const envFile = resolve(root, ".env.showcase.local");
const storageRoot = resolve(root, ".local-data/showcase-uploads");
const npmCommand = process.platform === "win32" ? "npm.cmd" : "npm";

const allowedModes = new Set(["start", "reset", "stop", "destroy", "status"]);
if (!allowedModes.has(mode)) {
  console.error(`Unknown showcase command: ${mode}`);
  process.exit(2);
}

function fail(message, cause) {
  console.error(`\n[showcase] ${message}`);
  if (cause instanceof Error) console.error(cause.message);
  process.exit(1);
}

function run(command, args, options = {}) {
  const result = spawnSync(command, args, {
    cwd: root,
    env: options.env ?? process.env,
    stdio: options.capture ? ["ignore", "pipe", "pipe"] : "inherit",
    encoding: "utf8",
  });
  if (result.error) throw result.error;
  if (result.status !== 0) {
    const detail = options.capture ? `${result.stdout ?? ""}${result.stderr ?? ""}`.trim() : "";
    throw new Error(`${command} ${args.join(" ")} failed${detail ? `:\n${detail}` : ""}`);
  }
  return String(result.stdout ?? "").trim();
}

function dockerArgs(...args) {
  return ["compose", "-p", composeProject, "-f", composeFile, ...args];
}

function parseEnvFile(content) {
  const values = {};
  for (const rawLine of content.split(/\r?\n/)) {
    const line = rawLine.trim();
    if (!line || line.startsWith("#")) continue;
    const separator = line.indexOf("=");
    if (separator < 1) continue;
    values[line.slice(0, separator)] = line.slice(separator + 1);
  }
  return values;
}

function generatedPassword() {
  return `Foundry-${randomBytes(9).toString("base64url")}!`;
}

async function loadOrCreateShowcaseEnv() {
  if (existsSync(envFile)) {
    const parsed = parseEnvFile(await readFile(envFile, "utf8"));
    const required = [
      "SHOWCASE_POSTGRES_PORT",
      "SHOWCASE_APP_PORT",
      "SHOWCASE_EXECUTOR_PORT",
      "DATABASE_URL",
      "AUTH_SECRET",
      "SHOWCASE_PASSWORD",
      "COMPONENT_EXECUTOR_SERVICE_TOKEN",
    ];
    const missing = required.filter((key) => !parsed[key]);
    if (missing.length) {
      throw new Error(`Existing .env.showcase.local is incomplete: ${missing.join(", ")}. Run npm run showcase:destroy to regenerate it.`);
    }
    return parsed;
  }

  const postgresPort = process.env.SHOWCASE_POSTGRES_PORT ?? "55432";
  const appPort = process.env.SHOWCASE_APP_PORT ?? "3100";
  const executorPort = process.env.SHOWCASE_EXECUTOR_PORT ?? "3202";
  const databaseUrl = `postgresql://postgres:postgres@127.0.0.1:${postgresPort}/learning_foundry_showcase`;
  const values = {
    SHOWCASE_POSTGRES_PORT: postgresPort,
    SHOWCASE_APP_PORT: appPort,
    SHOWCASE_EXECUTOR_PORT: executorPort,
    DATABASE_URL: databaseUrl,
    PRODUCT_DATABASE_URL: databaseUrl,
    CHECKPOINT_DATABASE_URL: databaseUrl,
    AUTH_DATABASE_URL: databaseUrl,
    WORKER_DATABASE_URL: databaseUrl,
    MIGRATION_DATABASE_URL: databaseUrl,
    CHECKPOINT_MIGRATION_DATABASE_URL: databaseUrl,
    AUTH_SECRET: randomBytes(48).toString("base64url"),
    AUTH_TRUST_HOST: "true",
    AUTH_URL: `http://127.0.0.1:${appPort}`,
    SYNTHETIC_SHOWCASE_MODE: "true",
    SHOWCASE_PASSWORD: generatedPassword(),
    FILE_STORAGE_LOCAL_ROOT: ".local-data/showcase-uploads",
    COMPONENT_EXECUTOR_SERVICE_URL: `http://127.0.0.1:${executorPort}`,
    COMPONENT_EXECUTOR_SERVICE_TOKEN: randomBytes(32).toString("hex"),
    DEEPSEEK_API_KEY: "",
    OPENAI_API_KEY: "",
    COHERE_API_KEY: "",
    LANGSMITH_TRACING: "false",
  };
  const content = [
    "# Generated by npm run showcase. Local synthetic data only.",
    "# Delete with npm run showcase:destroy to generate new credentials.",
    ...Object.entries(values).map(([key, value]) => `${key}=${value}`),
    "",
  ].join("\n");
  await writeFile(envFile, content, { encoding: "utf8", mode: 0o600 });
  try { await chmod(envFile, 0o600); } catch { /* Windows does not expose POSIX modes. */ }
  return values;
}

function assertNodeVersion() {
  const [major, minor] = process.versions.node.split(".").map(Number);
  if (major < 20 || (major === 20 && minor < 9)) {
    throw new Error(`Node.js >=20.9.0 is required; found ${process.versions.node}`);
  }
}

function ensureDocker() {
  run("docker", ["compose", "version"], { capture: true });
  run("docker", ["info"], { capture: true });
}

async function waitForPostgres(composeEnv) {
  for (let attempt = 0; attempt < 60; attempt += 1) {
    const result = spawnSync("docker", dockerArgs("exec", "-T", "postgres", "pg_isready", "-U", "postgres", "-d", "learning_foundry_showcase"), {
      cwd: root,
      env: composeEnv,
      stdio: "ignore",
    });
    if (result.status === 0) return;
    await new Promise((resolveDelay) => setTimeout(resolveDelay, 1_000));
  }
  throw new Error("PostgreSQL did not become ready within 60 seconds");
}

async function resetProductState(composeEnv) {
  const sql = [
    "DROP SCHEMA IF EXISTS foundry_checkpoint_private CASCADE;",
    "DROP SCHEMA IF EXISTS foundry_private CASCADE;",
    "DROP SCHEMA IF EXISTS langgraph_checkpoint CASCADE;",
    "DROP SCHEMA IF EXISTS foundry_operational CASCADE;",
    "DROP SCHEMA IF EXISTS foundry_product CASCADE;",
  ].join(" ");
  run("docker", dockerArgs("exec", "-T", "postgres", "psql", "-U", "postgres", "-d", "learning_foundry_showcase", "-v", "ON_ERROR_STOP=1", "-c", sql), { env: composeEnv });
  await rm(storageRoot, { recursive: true, force: true });
  await mkdir(storageRoot, { recursive: true });
}

function ensureDependencies() {
  const nextBinary = resolve(root, "node_modules", ".bin", process.platform === "win32" ? "next.cmd" : "next");
  if (!existsSync(nextBinary)) {
    console.log("\n[showcase] Installing locked dependencies with npm ci…");
    run(npmCommand, ["ci"]);
  }
}

async function assertPortAvailable(port, label) {
  await new Promise((resolveCheck, rejectCheck) => {
    const server = net.createServer();
    server.once("error", (error) => rejectCheck(new Error(`${label} port ${port} is already in use: ${error.message}`)));
    server.listen(Number(port), "127.0.0.1", () => server.close(resolveCheck));
  });
}

async function waitForHttp(url, timeoutMs) {
  const deadline = Date.now() + timeoutMs;
  let lastError;
  while (Date.now() < deadline) {
    try {
      const response = await fetch(url, { cache: "no-store" });
      if (response.ok) return response;
      lastError = new Error(`${url} returned ${response.status}`);
    } catch (error) {
      lastError = error;
    }
    await new Promise((resolveDelay) => setTimeout(resolveDelay, 750));
  }
  throw new Error(`Timed out waiting for ${url}${lastError instanceof Error ? `: ${lastError.message}` : ""}`);
}

function openBrowser(url) {
  if (process.env.SHOWCASE_NO_OPEN === "true") return;
  const command = process.platform === "darwin" ? "open" : process.platform === "win32" ? "cmd" : "xdg-open";
  const args = process.platform === "win32" ? ["/c", "start", "", url] : [url];
  try {
    const child = spawn(command, args, { detached: true, stdio: "ignore" });
    child.unref();
  } catch {
    // The URL is still printed for environments without a desktop opener.
  }
}

function printCredentials(values) {
  const appUrl = `http://127.0.0.1:${values.SHOWCASE_APP_PORT}`;
  console.log(`\nLearning Foundry local showcase is ready:\n  ${appUrl}/sign-in\n`);
  console.log("Institution: checkpoint-showcase");
  console.log(`Password:    ${values.SHOWCASE_PASSWORD}`);
  console.log("Accounts:");
  console.log("  learner@showcase.invalid");
  console.log("  teacher@showcase.invalid");
  console.log("  expert@showcase.invalid");
  console.log("  engineer@showcase.invalid");
  console.log("\nUse separate browser profiles or private windows for multiple roles.");
  console.log("Press Ctrl+C to stop Next.js and Component Executor; PostgreSQL data is preserved.");
  console.log("Run npm run showcase:reset for a clean seeded state or npm run showcase:destroy to remove all local showcase data.\n");
  openBrowser(`${appUrl}/sign-in`);
}

async function startForeground(values, appEnv) {
  await assertPortAvailable(values.SHOWCASE_EXECUTOR_PORT, "Component Executor");
  await assertPortAvailable(values.SHOWCASE_APP_PORT, "Next.js");

  const executorEnv = {
    ...appEnv,
    COMPONENT_EXECUTOR_PRODUCT_DATABASE_URL: values.DATABASE_URL,
    COMPONENT_EXECUTOR_DATABASE_URL: values.DATABASE_URL,
    COMPONENT_EXECUTOR_HOST: "127.0.0.1",
    COMPONENT_EXECUTOR_PORT: values.SHOWCASE_EXECUTOR_PORT,
  };

  const children = [];
  const executor = spawn(npmCommand, ["run", "component-executor"], { cwd: root, env: executorEnv, stdio: "inherit" });
  children.push(executor);
  await waitForHttp(`http://127.0.0.1:${values.SHOWCASE_EXECUTOR_PORT}/health`, 30_000);

  const app = spawn(npmCommand, ["run", "dev", "--", "--hostname", "127.0.0.1", "--port", values.SHOWCASE_APP_PORT], { cwd: root, env: appEnv, stdio: "inherit" });
  children.push(app);
  await waitForHttp(`http://127.0.0.1:${values.SHOWCASE_APP_PORT}/api/health`, 120_000);
  printCredentials(values);

  let shuttingDown = false;
  const shutdown = (exitCode = 0) => {
    if (shuttingDown) return;
    shuttingDown = true;
    for (const child of children) {
      if (!child.killed) child.kill("SIGTERM");
    }
    setTimeout(() => process.exit(exitCode), 250).unref();
  };

  process.once("SIGINT", () => shutdown(0));
  process.once("SIGTERM", () => shutdown(0));
  executor.once("exit", (code, signal) => {
    if (!shuttingDown) {
      console.error(`[showcase] Component Executor exited unexpectedly (${signal ?? code ?? "unknown"}).`);
      shutdown(code || 1);
    }
  });
  app.once("exit", (code, signal) => {
    if (!shuttingDown) {
      console.error(`[showcase] Next.js exited unexpectedly (${signal ?? code ?? "unknown"}).`);
      shutdown(code || 1);
    }
  });

  await new Promise(() => {});
}

try {
  assertNodeVersion();
  ensureDocker();
  const values = await loadOrCreateShowcaseEnv();
  const composeEnv = { ...process.env, SHOWCASE_POSTGRES_PORT: values.SHOWCASE_POSTGRES_PORT };

  if (mode === "status") {
    run("docker", dockerArgs("ps"), { env: composeEnv });
    process.exit(0);
  }
  if (mode === "stop") {
    run("docker", dockerArgs("stop"), { env: composeEnv });
    console.log("[showcase] PostgreSQL stopped. Foreground app processes must be stopped with Ctrl+C in their terminal.");
    process.exit(0);
  }
  if (mode === "destroy") {
    run("docker", dockerArgs("down", "-v", "--remove-orphans"), { env: composeEnv });
    await rm(storageRoot, { recursive: true, force: true });
    await rm(envFile, { force: true });
    console.log("[showcase] Removed the dedicated PostgreSQL volume, uploads and generated local credentials.");
    process.exit(0);
  }

  console.log("[showcase] Starting dedicated PostgreSQL…");
  run("docker", dockerArgs("up", "-d", "postgres"), { env: composeEnv });
  await waitForPostgres(composeEnv);
  if (mode === "reset") {
    console.log("[showcase] Resetting only the dedicated learning_foundry_showcase schemas and uploads…");
    await resetProductState(composeEnv);
  }

  ensureDependencies();
  await mkdir(storageRoot, { recursive: true });
  const appEnv = { ...process.env, ...values, NODE_ENV: "development" };

  console.log("[showcase] Applying Product State and LangGraph checkpoint migrations…");
  run(npmCommand, ["run", "db:migrate"], { env: appEnv });
  run(npmCommand, ["run", "db:checkpoint"], { env: appEnv });
  console.log("[showcase] Seeding isolated synthetic learner, teacher, expert and engineer accounts…");
  run(npmCommand, ["run", "db:seed"], { env: appEnv });

  await startForeground(values, appEnv);
} catch (error) {
  fail("Local showcase startup failed.", error);
}
